// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO1XuQlM7ZdvxG5me0wwSz8ZYCVP979HQ',
    appId: '1:367075543538:web:5564f4b378a484cfd8036b',
    messagingSenderId: '367075543538',
    projectId: 'bit-harvesting',
    authDomain: 'bit-harvesting.firebaseapp.com',
    databaseURL: 'https://bit-harvesting-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bit-harvesting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_-ZFWbzdRpXV_7cYMIMr_gFx1-PTojw',
    appId: '1:367075543538:android:48054d6e9ee5585ad8036b',
    messagingSenderId: '367075543538',
    projectId: 'bit-harvesting',
    databaseURL: 'https://bit-harvesting-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bit-harvesting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6CXdYHi7xc2L7cL5ZT9NbWEd71Jc-hcM',
    appId: '1:367075543538:ios:ee6bde31c0edd6abd8036b',
    messagingSenderId: '367075543538',
    projectId: 'bit-harvesting',
    databaseURL: 'https://bit-harvesting-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bit-harvesting.appspot.com',
    androidClientId: '367075543538-urvpaivvf2jjudoronc4j9k97bifpdbb.apps.googleusercontent.com',
    iosClientId: '367075543538-2njturua4brv9boo1muoiljmk80clfkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitHarvesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6CXdYHi7xc2L7cL5ZT9NbWEd71Jc-hcM',
    appId: '1:367075543538:ios:85fd91dd2baf25e4d8036b',
    messagingSenderId: '367075543538',
    projectId: 'bit-harvesting',
    databaseURL: 'https://bit-harvesting-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bit-harvesting.appspot.com',
    androidClientId: '367075543538-urvpaivvf2jjudoronc4j9k97bifpdbb.apps.googleusercontent.com',
    iosClientId: '367075543538-fem0hrpsabsd0tbtm9effqcde132nc2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitHarvesting.RunnerTests',
  );
}
